# Generated by Django 5.1.7 on 2025-10-01 08:11

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Messaggio di errore')),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo di eccezione')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e ora')),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Dati aggiuntivi (es. stack trace)')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
