# Generated by Django 3.2.20 on 2025-05-20 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '0001_initial'),
        ('ticket_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Titolo report')),
                ('report_description', models.CharField(max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Descrizione report')),
                ('report_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project', verbose_name='Progetto')),
                ('report_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_manager.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report',
                'ordering': ('report_title',),
            },
        ),
    ]
