# Generated by Codex on 2026-02-11
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_alter_workspace_id_alter_workspaceuser_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("colors", models.JSONField(blank=True, default=dict, null=True)),
                ("logo_full", models.ImageField(blank=True, null=True, upload_to="branding/logos/")),
                ("logo_compact", models.ImageField(blank=True, null=True, upload_to="branding/logos/")),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="branding/favicons/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding_settings",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding Settings",
                "verbose_name_plural": "Branding Settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
