# Generated by Django 5.1.7 on 2025-10-14 22:27

import base_modules.mailer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, help_text='Se vuoto usa DEFAULT_FROM_EMAIL', max_length=254, null=True)),
                ('to', models.JSONField(default=base_modules.mailer.models.default_list, help_text="Lista destinatari, es: ['a@b.it','c@d.it']")),
                ('cc', models.JSONField(blank=True, default=base_modules.mailer.models.default_list)),
                ('bcc', models.JSONField(blank=True, default=base_modules.mailer.models.default_list)),
                ('subject', models.CharField(blank=True, default='', help_text='Può essere valorizzato da template', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1=alta, 5=bassa (puramente informativa)')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('subject_template', models.TextField(help_text="Esempio: 'Ciao {{ user.first_name }}'")),
                ('html_template', models.TextField(help_text='HTML con variabili: {{ ... }}')),
                ('text_template', models.TextField(blank=True, default='', help_text='Fallback testuale (opzionale)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('mimetype', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.email')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.emailtemplate'),
        ),
    ]
