# Generated by Django 5.1.7 on 2025-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='La chiave della configurazione', max_length=100)),
                ('value', models.TextField(help_text='Il valore della configurazione')),
                ('description', models.TextField(blank=True, help_text='Descrizione della configurazione (opzionale)', null=True)),
            ],
        ),
    ]
