# Generated by Django 5.1.7 on 2025-08-27 22:41

import base_modules.user_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=base_modules.user_manager.models.user_directory_path),
        ),
    ]
