# Generated by Django 5.1.7 on 2025-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(100, 'SuperAdmin'), (50, 'Admin'), (10, 'Utente'), (5, 'Employee')], default=1, verbose_name='User permission level'),
        ),
    ]
