# Generated by Django 5.1.7 on 2026-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_alter_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(100, 'SuperAdmin'), (50, 'Associate'), (10, 'Utente'), (5, 'Employee')], default=1, verbose_name='User permission level'),
        ),
    ]
