# Generated by Django 5.1.7 on 2026-01-22 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_manager_accounts', '0001_initial'),
        ('finance_manager_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Budget limit or target amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Target Value')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='Period')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percentage of budget at which to trigger an alert', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Alert Threshold (%)')),
                ('start_date', models.DateField(help_text='When this budget becomes active', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for ongoing budget', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Leave empty to apply budget across all accounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_manager_accounts.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_manager_core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-start_date', 'category__name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='finance_man_categor_2abdc2_idx'), models.Index(fields=['start_date', 'end_date'], name='finance_man_start_d_0e8ec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Rule Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gross Amount')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT Percentage')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='Transaction Type')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bi-monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='For monthly/quarterly/annual: which day of the month', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of Month')),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='For weekly: 0=Monday, 6=Sunday', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Day of Week')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for indefinite recurrence', null=True, verbose_name='End Date')),
                ('last_generated_date', models.DateField(blank=True, help_text='Date of the last automatically generated transaction', null=True, verbose_name='Last Generated Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('generate_as_hypothetical', models.BooleanField(default=False, help_text='Create future transactions as hypothetical for forecasting', verbose_name='Generate as Hypothetical')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='finance_manager_accounts.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='finance_manager_core.category', verbose_name='Category')),
                ('template_transaction', models.ForeignKey(blank=True, help_text='The transaction to use as a template for recurring copies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_template', to='finance_manager_core.transaction', verbose_name='Template Transaction')),
            ],
            options={
                'verbose_name': 'Recurrence Rule',
                'verbose_name_plural': 'Recurrence Rules',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'start_date'], name='finance_man_is_acti_1fbef8_idx'), models.Index(fields=['frequency'], name='finance_man_frequen_4b976b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tax Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tax Rate (%)')),
                ('applicable_to', models.CharField(choices=[('income', 'Income Only'), ('expense', 'Expenses Only'), ('all', 'All Transactions'), ('category', 'Specific Categories')], default='income', max_length=20, verbose_name='Applicable To')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount before this tax applies', max_digits=15, null=True, verbose_name='Threshold Amount')),
                ('is_progressive', models.BooleanField(default=False, help_text='Tax rate applies only to amount above threshold', verbose_name='Progressive Tax')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, help_text='Leave empty if currently valid', null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text="Only used when 'Applicable To' is set to 'Specific Categories'", related_name='tax_configs', to='finance_manager_core.category', verbose_name='Applicable Categories')),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'valid_from'], name='finance_man_is_acti_24f842_idx'), models.Index(fields=['applicable_to'], name='finance_man_applica_485cf0_idx')],
            },
        ),
    ]
