# Generated by Django 3.2.20 on 2025-05-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(max_length=255, verbose_name='Nome Workspace')),
                ('workspace_description', models.TextField(blank=True, null=True, verbose_name='Descrizione Workspace')),
                ('workspace_logo', models.FileField(blank=True, null=True, upload_to='workspace_logos/', verbose_name='Logo Workspace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['workspace_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=50, verbose_name='Ruolo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data di Adesione')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Utente Workspace',
                'verbose_name_plural': 'Utenti Workspace',
                'ordering': ['workspace', 'user'],
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
