# Generated by Django 3.2.20 on 2025-05-20 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Titolo')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data inizio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data fine')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Note')),
                ('link_streaming', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link streaming')),
                ('insert_date', models.DateField(auto_now_add=True, null=True, verbose_name='Data Inserimento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_meeting', to=settings.AUTH_USER_MODEL)),
                ('insert_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insert_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meeting',
                'ordering': ('start_date',),
            },
        ),
    ]
