# Generated by Django 3.2.20 on 2025-07-04 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durata'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='included_in_subscription',
            field=models.BooleanField(default=False, verbose_name='Incluso in abbonamento'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='users_meeting',
            field=models.ManyToManyField(blank=True, related_name='user_meeting', to=settings.AUTH_USER_MODEL, verbose_name='Utenti Meeting'),
        ),
    ]
