# Generated by Django 3.2.20 on 2025-07-07 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20250704_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='AI Summary'),
        ),
    ]
