# Generated by Django 5.1.7 on 2025-10-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('label', models.CharField(choices=[('google_drive', 'Google Drive'), ('figma', 'Figma'), ('google_doc', 'Google Doc'), ('google_spreadsheet', 'Google Spreadsheet'), ('github', 'GitHub'), ('wetransfer', 'WeTransfer'), ('altro', 'Altro')], db_index=True, default='altro', max_length=50)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['label'], name='links_link_label_48dbad_idx'), models.Index(fields=['content_type', 'object_id'], name='links_link_content_ff4360_idx')],
            },
        ),
    ]
