# Generated by Django 5.1.7 on 2026-02-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content_sid', models.CharField(blank=True, default='', help_text='Twilio Content SID for approved template', max_length=50)),
                ('body_template', models.TextField(help_text='Template body with placeholders ({{1}}, {{2}}, etc.)')),
                ('language', models.CharField(default='it', max_length=10)),
                ('category', models.CharField(default='utility', help_text='Template category (utility, marketing, authentication)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_phone', models.CharField(db_index=True, help_text='Phone number in E.164 format (e.g., +393401234567)', max_length=20)),
                ('twilio_phone', models.CharField(help_text='Twilio WhatsApp sender number (e.g., +14155238886)', max_length=20)),
                ('participant_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Associated system user (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-last_message_at'],
                'unique_together': {('participant_phone', 'twilio_phone')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, db_index=True, help_text='Twilio Message SID', max_length=50, null=True, unique=True)),
                ('body', models.TextField(blank=True, default='', help_text='Text content of the message')),
                ('media_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs attached to the message')),
                ('media_content_types', models.JSONField(blank=True, default=list, help_text='List of media content types')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (received)'), ('outbound', 'Outbound (sent)')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=15)),
                ('error_code', models.CharField(blank=True, default='', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Twilio webhook')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='twilio.whatsappconversation')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
