# Generated by Django 3.2.20 on 2025-05-20 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '0001_initial'),
        ('attachment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta')], max_length=10, null=True, verbose_name='Priority')),
                ('hours_estimation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hours estimation')),
                ('opening_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opening date')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Closing date')),
                ('cost_estimation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('status', models.CharField(blank=True, choices=[('open', 'Aperto'), ('in_progress', 'In corso'), ('resolved', 'Risolto'), ('closed', 'Chiuso')], default='open', max_length=20, null=True)),
                ('expected_resolution_date', models.DateTimeField(blank=True, null=True)),
                ('expected_action', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Comportamento atteso')),
                ('real_action', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Comportamento vero')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assegnatario', to=settings.AUTH_USER_MODEL, verbose_name='Assignees')),
                ('attachments', models.ManyToManyField(blank=True, related_name='ticket_attachments', to='attachment.Attachment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetto', to='project_manager.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('opening_date',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500000, verbose_name='Testo del Messaggio')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('attachments', models.ManyToManyField(blank=True, related_name='message_attachments', to='attachment.Attachment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket_manager.ticket')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('insert_date',),
            },
        ),
    ]
