# Generated by Django 3.2.20 on 2025-07-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_ticket_ticket_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_linked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_ticket', to='ticket_manager.ticket', verbose_name='Linked Ticket'),
        ),
    ]
