# Generated by Django 3.2.20 on 2025-07-11 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_manager', '0003_ticket_ticket_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'USER_LEVEL__in': [50, 100]}, related_name='assegnatario', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
