# Generated by Django 5.1.7 on 2025-08-27 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0004_alter_ticket_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'permission__in': [50, 100]}, related_name='assegnatario', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
