# Generated by Django 5.1.7 on 2025-10-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0005_alter_ticket_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payments_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('evo', 'Evolutiva')], default='bug', max_length=20, null=True),
        ),
    ]
