# Generated by Django 5.1.7 on 2025-10-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0006_ticket_payments_status_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hours_estimation',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Hours estimation'),
        ),
    ]
