# Generated by Django 5.1.7 on 2025-10-25 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
        ('project_manager', '0003_project_month_cost_limit'),
        ('ticket_manager', '0007_alter_ticket_hours_estimation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In corso'), ('blocked', 'Bloccato'), ('done', 'Completato'), ('canceled', 'Annullato')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta')], db_index=True, default='medium', max_length=10)),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(blank=True, related_name='task_attachments', to='attachment.attachment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ticket_manager.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_manager.project')),
                ('ticket', models.ForeignKey(blank=True, help_text='Ticket di origine, se deriva da richiesta cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ticket_manager.ticket')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'priority'], name='ticket_mana_status_c938ce_idx'), models.Index(fields=['project', 'status'], name='ticket_mana_project_aab02d_idx')],
            },
        ),
    ]
