# Generated by Django 5.1.7 on 2025-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0009_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('evo', 'Evolutiva'), ('check', 'Check'), ('aggiornamento', 'Aggiornamento')], default='bug', max_length=20, null=True),
        ),
    ]
