# Generated by Django 5.1.7 on 2026-01-22 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_manager_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('color', models.CharField(default='#3498db', help_text='Hex color code for UI display (e.g., #3498db)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g., FontAwesome class or Material icon name)', max_length=50, null=True, verbose_name='Icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('transaction_type', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Restrict this category to a specific transaction type', max_length=10, null=True, verbose_name='Default Transaction Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for top-level categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance_manager_core.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Positive value; transaction type determines direction', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gross Amount')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT/Tax percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='VAT Percentage')),
                ('competence_date', models.DateField(help_text='The date the transaction is attributed to (accounting date)', verbose_name='Competence Date')),
                ('payment_date', models.DateField(blank=True, help_text='The actual date of payment (leave empty if not yet paid)', null=True, verbose_name='Payment Date')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('is_hypothetical', models.BooleanField(default=False, help_text='Mark as hypothetical for cashflow forecasting scenarios', verbose_name='Hypothetical')),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('import_csv', 'CSV Import'), ('import_excel', 'Excel Import'), ('import_bank', 'Bank Statement Import'), ('recurring', 'Recurring Transaction'), ('api', 'API Integration')], default='manual', max_length=20, verbose_name='Data Source')),
                ('external_reference', models.CharField(blank=True, help_text='Reference ID from external system (bank statement, invoice, etc.)', max_length=200, null=True, verbose_name='External Reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance_manager_accounts.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance_manager_core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-competence_date', '-created_at'],
            },
        ),
    ]
