# Generated by Django 5.1.7 on 2026-01-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_manager_core', '0001_initial'),
        ('finance_manager_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance_manager_planning.recurrencerule', verbose_name='Recurrence Rule'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='finance_man_parent__426d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status'], name='finance_man_account_a04623_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'transaction_type'], name='finance_man_categor_b067d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['competence_date'], name='finance_man_compete_d09938_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_date'], name='finance_man_payment_e512aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_hypothetical', 'status'], name='finance_man_is_hypo_ddff26_idx'),
        ),
    ]
