# Generated by Django 5.1.7 on 2025-10-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_quote_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_quote_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_quote_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
