# Generated by Django 5.1.7 on 2025-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_project_hours_quote_max_project_hours_quote_mid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='month_cost_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
