# Generated by Django 5.1.7 on 2026-01-22 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('abi_code', models.CharField(blank=True, help_text='Italian bank ABI code (5 digits)', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'ABI code must be exactly 5 digits')], verbose_name='ABI Code')),
                ('swift_code', models.CharField(blank=True, help_text='International SWIFT/BIC code (8-11 characters)', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$', 'Invalid SWIFT/BIC format')], verbose_name='SWIFT/BIC Code')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True, verbose_name='Country Code')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Account Name')),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$', 'Invalid IBAN format')], verbose_name='IBAN')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when the account was added to the system', max_digits=15, verbose_name='Initial Balance')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('JPY', 'Japanese Yen (¥)')], default='EUR', max_length=3, verbose_name='Currency')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account'), ('cash', 'Physical Cash'), ('investment', 'Investment Account'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='checking', max_length=50, verbose_name='Account Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('include_in_totals', models.BooleanField(default=True, help_text='Include this account when calculating aggregate balances', verbose_name='Include in Totals')),
                ('color', models.CharField(blank=True, help_text='Hex color code for UI display (e.g., #3498db)', max_length=7, null=True, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, help_text='Leave empty for cash/physical reserves', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance_manager_accounts.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'include_in_totals'], name='finance_man_is_acti_a3d8fd_idx')],
            },
        ),
    ]
