# Generated by Django 4.x on 2026-02-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('base_url', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.TextField()),
                ('finished_at', models.TextField(blank=True, null=True)),
                ('root_url', models.TextField(blank=True, null=True)),
                ('config_json', models.TextField()),
                ('schedule', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('total_urls', models.IntegerField(default=0)),
                ('issues_summary', models.TextField(default='{}')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='runs', to='per_seo.site')),
            ],
            options={
                'db_table': 'runs',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('lastmod', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('issues_count', models.IntegerField(blank=True, null=True)),
                ('diagnostics_json', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField()),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='per_seo.run')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='per_seo.site')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='SiteSitemap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sitemap_url', models.TextField()),
                ('created_at', models.TextField()),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sitemaps', to='per_seo.site')),
            ],
            options={
                'db_table': 'site_sitemaps',
            },
        ),
        migrations.CreateModel(
            name='PageIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.TextField()),
                ('issue_code', models.TextField()),
                ('severity', models.TextField()),
                ('message', models.TextField()),
                ('detected_at', models.TextField()),
                ('resolved_at', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='per_seo.page')),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.DO_NOTHING, to='per_seo.run')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.DO_NOTHING, to='per_seo.site')),
            ],
            options={
                'db_table': 'page_issues',
            },
        ),
    ]
